default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

