version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      
      MYSQL_DATABASE: mydata
      MYSQL_USER: admin11
      MYSQL_PASSWORD: pass11
      MYSQL_ROOT_PASSWORD: pass11
      MYSQL_ALLOW_EMPTY_PASSWORD: pass11
      MYSQL_RANDOM_ROOT_PASSWORD: pass11

    ports:
      - "3306:3306"
    volumes:
      - .:/app

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    networks: 
      - "devsinc"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    links :
      - db
    environment:    
      db_USER: root
      db_NAME: mydata
      db_PASSWORD: pass11
      db_HOST: db 

networks:
  devsinc:
